name: Nebula MCP

services:
  postgres:
    image: postgres:latest
    container_name: nebula-postgres
    ports:
      - 5432:5432
    networks:
      - nebula
    volumes:
      - nebula_pgData:/var/lib/postgresql/MAJOR/docker
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:latest
    container_name: nebula-redis-server
    ports:
      - 6379:6379
    networks:
      - nebula
    volumes:
      - nebula_redis:/data
  redis_insight:
    depends_on:
      - "redis"
    image: redis/redisinsight:latest
    container_name: nebula-redisinsight
    volumes:
      - nebula_redisinsight:/data
    ports:
      - 5540:5540
    networks:
      - nebula
    environment:
      - RI_REDIS_HOST_0=nebula-redis-server
      - RI_REDIS_PORT_0=6379
      - RI_REDIS_USERNAME_0=default
      - RI_REDIS_PASSWORD_0=default
  mongodb:
      image: mongodb/mongodb-atlas-local:preview
      hostname: mongodb
      environment:
         - MONGODB_INITDB_ROOT_USERNAME=admin
         - MONGODB_INITDB_ROOT_PASSWORD=admin
         - VOYAGE_API_KEY=${VOYAGE_AI_API_KEY}
      ports:
         - 27017:27017
      networks:
         - nebula
      volumes:
         - ./init:/docker-entrypoint-initdb.d
         - mongoDb:/data/db
         - configMongoDb:/data/configdb
         - mongot:/data/mongot

networks:
  nebula:
    driver: bridge
    name: nebula

volumes:
  nebula_pgData:
  nebula_redis:
  nebula_redisinsight:
  mongoDb:
  configMongoDb:
  mongot:
